# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Matt McCormick - AI & Web Developer
email: matt.c.mccormick@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Matt McCormick is a highly skilled AI and full-stack web developer, specializing in Python, OpenAI, and startup development. This site showcases his expertise, projects, and articles on cutting-edge AI solutions and web development. Stay up-to-date with Matt's work, discover valuable resources, and connect with a top AI consultant to help you build your next big idea.
baseurl: "" # the subpath of your site, e.g. /blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mmccormick.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: MattCMcCormick
github_username:  MMcCormick

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-data

# Google Analytics
google_analytics: G-F5WTVK9VVQ

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
